using Content.Client.Administration.UI.CustomControls;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;

namespace Content.Client.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class QuickTestWindow : DefaultWindow
{
    public QuickTestWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}

[UsedImplicitly]
internal sealed class QuickTestWindowCommand : LocalizedCommands
{
    public override string Command => "testwindow";

    public override void Execute(IConsoleShell shell, string argStr, string[] args)
    {
        var window = new QuickTestWindow();
        window.OpenCentered();
    }
}

